### PR TITLE
fix(android): declare namespace / buildconfig options for gradle plugin 8+ compatibility

### LINKED ISSUE #328: Build failed for Android with RN 0.73.0-rc.1 and 0.73.0-rc.2
System Information:

```
System:
  OS: macOS 14.0
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 740.56 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.7.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0-rc.1
    wanted: 0.73.0-rc.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

Resultat:
```
% npx react-native run-android

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':invertase_react-native-apple-authentication'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
     
     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 33s
error Failed to install the app.
```

### PR DESCRIPTION
**Pull request by ivanignatiev**
Change is required as per announce in community: https://github.com/react-native-community/discussions-and-proposals/issues/671

Fixes #328

### CODE REVIEW

**Comment by OHHAKO** [comment]
@ivanignatiev hi, thanks for fixing it! you specified the agp version. but why? 
I contributed to another repository, but didn't use the terms like you. Because of course I didn't know it was necessary.

>   def agpVersion = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION
  if (agpVersion.tokenize('.')[0].toInteger() >= 7)

**Comment by ivanignatiev** [comment]
@OHHAKO hi ! 

I am not sure that it is really really necessary (I am not Java/Grandle expert). Before React Native requirements upgrades, the namespace was taken from AndroidManifest.xml. 

For me, it is just a safe formula for backward compatibility for guys who will use the module with older versions of React Native.

**Review by mikehardy — APPROVED** [review]
The reason to specify the version is so that react-native less than 0.66 still works, as it uses gradle < 7 and gradle < 7 does not know about the namespace or buildconfig stuff

So this is a great change. Thanks for your patience! Just now getting to working on my main work app to check it for compatibility (which uses this module, and drives my interest in maintaining this module...)

**Comment by mikehardy** [comment]
After updating the example app + CI so things would actually build, I pulled this and ran it locally, and it works fine.
CI will check it after a merge to main as well

**Pull request merged**
