### PR TITLE
Import version from package.json - ./version does not exist

### PR DESCRIPTION
**Pull request by NestedLooper**
None of these files exist:
  * node_modules/@invertase/react-native-apple-authentication/lib/version(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@invertase/react-native-apple-authentication/lib/version/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)]

### CODE REVIEW

**Comment by mikehardy** [comment]
I do not believe this is an error, it is a part of the build infrastructure and should be handled on package install for you https://github.com/invertase/react-native-apple-authentication/blob/2fd0813de1006e28eccad7a55a8596424541c20c/package.json#L9

**Comment by NestedLooper** [comment]
I will look into it more. I get the same error (Unable to resolve module `./version` from `node_modules/@invertase/react-native-apple-authentication/lib/index.js`) whether I build from react-native or Xcode, simulator or device. 
React Native v0.63.3
react-native-apple-authentication v2.1.0

**Comment by mikehardy** [comment]
I believe the build step (and thus generation of version.js) should happen as part of package management during package install (yarn or npm i)

**Comment by dawntommm** [comment]
hi, getting same errors, would appreciate if you can share how to get rid of this

**Comment by mikehardy** [comment]
> I believe the build step (and thus generation of version.js) should happen as part of package management during package install (yarn or npm i)

So...do that step? Your package manager should have done it though:

https://github.com/invertase/react-native-apple-authentication/blob/2fd0813de1006e28eccad7a55a8596424541c20c/package.json#L9

**Comment by dawntommm** [comment]
thank you Mike, I did run `genversion --semi lib/version.js`, and I do have index.js && version.js in my folder
however, the error still not going away, not sure why compile does not find the file(even tho it is right there)

**Comment by mikehardy** [comment]
Sounds like you've got some cache corruption in the gigantic house of cards that is modern cross platform web development. Highly recommend giving `npx react-native-clean-project` a try but I always warn people if they are not on a good connection and they clean all the things you are in for a big download after. But you'll be clean...

**Pull request closed without merging**
