### PR TITLE
Export interfaces

### PR DESCRIPTION
**Pull request by mrousavy**
Need to use them for my function parameters.

### CODE REVIEW

**Comment by mrousavy** [comment]
That's my workaround to get the type for now:

```ts
	type ThenArg<T> = T extends PromiseLike<infer U> ? U : T;
	export type AppleAuthRequestResponse = ThenArg<ReturnType<typeof appleAuth.performRequest>>;
```

🧙

**Review by mikehardy — APPROVED** [review]
I can't see why not 😁

**Comment by mikehardy** [comment]
launched in v2.0.1 :rocket:

**Comment by mrousavy** [comment]
thanks! 🎉

**Pull request merged**
