### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by pvinis**

### CODE REVIEW

**Comment by pvinis** [comment]
CRINGE. if you are going to have a silly rule, at least show me the options!

**Comment by pvinis** [comment]
ok ive spent the time i should. enjoy the pr, feel free to fix the title and merge. bye.

**Review by Salakar — APPROVED** [review]

**Comment by mikehardy** [comment]
@pvinis the failing check included the reason - 

> Pull request has only one commit and it's not semantic; this may lead to a non-semantic commit in the base branch (see https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155). Amend the commit message to match the pull request title, or add another commit.

Okay, that has a busted link in it (cringe indeed), but for future reference since it's a general github issue, that's the problem. Even if you fix the PR title of a single-commit PR, because github defaults to the *commit* message for single-commit PRs when you go to squash them, it's dangerous for the commit itself not to be conventional as a maintainer may accidentally merge a non-conventional commit.

So there ya go :-), "TIL..." etc. Cheers

**Comment by pvinis** [comment]
sorry for the aggressiveness. I got triggered hard 😅.

I made the change in gh, and then the link was broken, I didn't read the thing correctly, then when I realized it's the commit, and I can't change the commit message on gh, I was like ok enough.

these checks are always better as a git hook for early feedback. if I make the PR it's already too late for me and many others. though I have no idea if and how git hooks work when making a commit on gh 🤔.

see you around 👍.

**Comment by mikehardy** [comment]
A great point re: hooks vs checks. I've been working towards including more hooks to match the checks in repos I managed but my GitHub Actions-fu is quite strong and my Git Hooks-fu is still pretty weak. But I'll see if I can cook up a semantic commit one as that would be nice.

I'm mostly replying to say I use upgrade-helper all.the.time so just taking the opportunity thank you again for it. Cheers

**Pull request merged**
