### PR TITLE
Add Auth0 Information to README

### PR DESCRIPTION
**Pull request by QuintonC**
Reference this issue comment from @mikehardy: https://github.com/invertase/react-native-apple-authentication/issues/113

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
This looks great! I have no problem with the documentation, but could I ask you to organize it differently? I'd like there to be an AUTH0.md file next to FIREBASE.md, and just link to it, in the same way as the firebase integration doc since they are roughly peers with regard to this package, and it will help keep the README from getting too big

**Comment by QuintonC** [comment]
> This looks great! I have no problem with the documentation, but could I ask you to organize it differently? I'd like there to be an AUTH0.md file next to FIREBASE.md, and just link to it, in the same way as the firebase integration doc since they are roughly peers with regard to this package, and it will help keep the README from getting too big

Sounds good! I can make changes later today and get an update to this PR made. Good feedback. Cheers 🍻

**Comment by QuintonC** [comment]
@mikehardy Updates have been made as requested. Sorry for the delay.

**Review by mikehardy — APPROVED** [review]
Fantastic! No worries on the delay of course - this will be a help to others I am sure, and maybe a future version of yourself even ;-)

**Pull request merged**
